simulation:
  seed: 42
  device: "cuda"
  steps: 10
  initial infection rate: 0.005
  start_vaccination: 80
  vaccine_rate_daily: 0.05

population:
  contacts_per_day: 30
  mask_factor: 0.5
  lockdown_factor: 0.4
  leave_prob: 0.001

variants:
    original_strain:
      P_base: 0.5
      recovery_day: 7
      death_prob: 0.02
      immunity_waning_rate: 0.005
      step_start: 0
      
distributions:
  susceptibility: {base: 0.7, variance: 0.3}
  noncompliance: {base: 0.2, variance: 0.8}
  mobility: {base: 0.5, variance: 0.5}
  age_factor: {base: 0.1, multiplier: 2.0}
